version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rag_core
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  # Redis cache
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
      
  # MinIO object storage
  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    
  # Weaviate vector database
  weaviate:
    image: semitechnologies/weaviate:1.30.13
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
      
  # RAG Core API
  rag-core-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
      - weaviate
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/rag_core
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - VECTOR_DB_URL=http://weaviate:8080
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    volumes:
      - .:/app
    
volumes:
  postgres_data:
  minio_data:
  weaviate_data: