# RAG Core System Configuration

database:
  url: "postgresql://user:password@localhost/rag_core"

vector_db:
  url: "http://172.28.86.42:28080"
  grpc_port: 50051

llm:
  provider: "local_api"  # 可选: "local_api", ...
  api_key: "your-api-key-here"
  model: "gpt-3.5-turbo"
  local_api:
    url: "http://172.16.89.10:9648/scbllm/llm-2025/llm_infer"

redis:
  url: "redis://localhost:6379/0"

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"

api:
  host: "0.0.0.0"
  port: 8001
  gradio_port: 7860

embedding:
  provider: "local_api"  # 可选: "local_api", "siliconflow"
  local_api:
    url: "http://172.16.89.10:10669/scbllm/embedding-infer/embedding"
  siliconflow:
    api_key: "your-siliconflow-api-key-here"
    model_name: "BAAI/bge-large-zh-v1.5"
    api_url: "https://api.siliconflow.cn/v1/embeddings"

rerank:
  provider: "local_api"  # 可选: "local_api"
  local_api:
    url: "http://172.16.89.10:10669/scbllm/embedding-infer/reranker"

# Logging configuration
logging:
  level: DEBUG
  console_level: DEBUG
  file_level: DEBUG
  file: logs/rag_core.log
  max_file_size: 10485760  # 10MB
  backup_count: 5
  format: "{time:YYYY-MM-DD HH:mm:ss} [{level}] {message}"
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # 模块级别日志控制 - 可以为不同模块设置不同的日志级别
  module_levels:
    # 核心模块
    parser: DEBUG
    chunking: DEBUG
    embedding: DEBUG
    vector: DEBUG
    retrieval: DEBUG
    reranker: DEBUG
    PromptEngine: DEBUG
    llm: DEBUG
    
    
    # Pipeline模块
    RAGPipeline: DEBUG
    DocumentProcessingPipeline: DEBUG
    
    # 其他模块
    default: INFO  # 默认级别

# Debug mode configuration
debug:
  enabled: true  # Set to true to enable debug logging for all modules

# RAG specific configuration
rag:
  chunk_size: 1000
  chunk_overlap: 200
  parse_by_chapter: true
  parse_by_element: false
  remove_hyperlinks: true
  remove_images: true
  enable_metadata: true
  parser_type: "mineru"  # Parser类型，"fast"或"mineru"
  mineru_parser_backend: "vlm-sglang-client"  # MineruParser的后端类型，"vlm-sglang-client"或"pipeline"
  batch_size: 32
  retrieve_top_k: 20
  rerank_top_n: 5
  
  # Markdown解析器配置
  markdown_clean_html: true
  markdown_preserve_html_imgs: false
  markdown_preserve_html_tables: true
  
  # 混合检索配置
  retrieval_type: "hybrid"  # 可选: "hybrid", "vector", "text"
  hybrid_config:
    vector_weight: 0.7      # 向量检索权重
    text_weight: 0.3        # 文本检索权重
